apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: us-west1-docker.pkg.dev/qwiklabs-gcp-00-cfbf8d981615/my-repository/hello-cloudbuild-dev:v1

        #image: <todo>
        #image: us-west1-docker.pkg.dev/qwiklabs-gcp-00-cfbf8d981615/my-repository/sample-app:v1.0
        ports:
        - containerPort: 8080
